//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FollowUpList()
        {
            this.Alerts = new HashSet<Alert>();
        }
    
        public long FollowUpListId { get; set; }
        public long ProductId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<long> FrequencyId { get; set; }
        public long AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Frequency Frequency { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alert> Alerts { get; set; }
    }
}
