//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpList
    {
        public long FollowUpListId { get; set; }
        public long ProductId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<long> FrequencyId { get; set; }
        public long AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Frequency Frequency { get; set; }
        public virtual Product Product { get; set; }
    }
}
