
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ProductToList
{

    public long ProductToListId_ { get; set; }

    public long ProductId { get; set; }

    public long ListId { get; set; }

    public Nullable<long> BuyerId { get; set; }

    public Nullable<System.DateTime> DateOfBuy { get; set; }

    public Nullable<int> Amount { get; set; }



    public virtual List List { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }

}

}
