
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ProductsToTypeList
{

    public long ProductId { get; set; }

    public long TypeListId { get; set; }

    public int Amount { get; set; }



    public virtual Product Product { get; set; }

    public virtual TypesList TypesList { get; set; }

}

}
